spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipesphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "1234"  # Replace with your actual password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: INFO
    edu.recipespire: DEBUG